package dictionary

type Language string

const (
	LanguageEnglish             Language = "english"
	LanguageAlbanian            Language = "albanian"
	LanguageArabic              Language = "arabic"
	LanguageBreton              Language = "breton"
	LanguageCatalan             Language = "catalan"
	LanguageChinese_simplified  Language = "chinese_simplified"
	LanguageChinese_traditional Language = "chinese_traditional"
	LanguageCorsican            Language = "corsican"
	LanguageCzech               Language = "czech"
	LanguageDanish              Language = "danish"
	LanguageDutch               Language = "dutch"
	LanguageEsperanto           Language = "esperanto"
	LanguageEstonian            Language = "estonian"
	LanguageFinnish             Language = "finnish"
	LanguageFrench              Language = "french"
	LanguageGaelic              Language = "gaelic"
	LanguageGeorgian            Language = "georgian"
	LanguageGerman              Language = "german"
	LanguageGreek               Language = "greek"
	LanguageHebrew              Language = "hebrew"
	LanguageHungarian           Language = "hungarian"
	LanguageIcelandic           Language = "icelandic"
	LanguageIndonesian          Language = "indonesian"
	LanguageItalian             Language = "italian"
	LanguageJapanese            Language = "japanese"
	LanguageKorean              Language = "korean"
	LanguageKurdish             Language = "kurdish"
	LanguageLatvian             Language = "latvian"
	LanguageLithuanian          Language = "lithuanian"
	LanguageMalagasy            Language = "malagasy"
	LanguageNorwegian           Language = "norwegian"
	LanguagePolish              Language = "polish"
	LanguagePortuguese_brazil   Language = "portuguese_brazil"
	LanguagePortuguese_portugal Language = "portuguese_portugal"
	LanguageRomanian            Language = "romanian"
	LanguageRussian             Language = "russian"
	LanguageSerbo_croat         Language = "serbo_croat"
	LanguageSlovak              Language = "slovak"
	LanguageSlovenian           Language = "slovenian"
	LanguageSpanish             Language = "spanish"
	LanguageSwahili             Language = "swahili"
	LanguageSwedish             Language = "swedish"
	LanguageTurkish             Language = "turkish"
	LanguageVietnamese          Language = "vietnamese"
	LanguageYiddish             Language = "yiddish"
	LanguageWalloon             Language = "walloon"
	LanguageWelsh               Language = "welsh"
)
